fpm:
    build: ./php56-fpm/
    container_name: php56-fpm
    environment:
      - TERM=xterm-256color
    volumes:
      - ~/Projekty/test-docker/:/opt

nginx:
    build: ./nginx/
    container_name: nginx
    environment:
      - TERM=xterm-256color
    volumes:
      - ./nginx/demo.conf:/etc/nginx/conf.d/default.conf
      - ~/Projekty/test-docker/:/opt
    links:
      - fpm

composer:
    build: ./composer/
    dockerfile: ./Dockerfile
    container_name: composer
    log_driver: syslog
    environment:
      - TERM=xterm-256color
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/Projekty/:/var/www
