nginx:
    build: ./nginx/
    container_name: nginx
    environment:
      - TERM=xterm-256color
    volumes:
      - ./nginx/demo.conf:/etc/nginx/conf.d/default.conf
      - ~/Projekty/test-docker/:/opt
    links:
      - fpm